// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYwiJkuTo6gjItTo73U9nV3d9dBhgAnPs',
    appId: '1:243311062615:web:e28991c7c895b307cefd12',
    messagingSenderId: '243311062615',
    projectId: 'fir-analytics-example-c69c7',
    authDomain: 'fir-analytics-example-c69c7.firebaseapp.com',
    storageBucket: 'fir-analytics-example-c69c7.appspot.com',
    measurementId: 'G-LXQF2CXFRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1WtKj-NGW8MJLbd_30DSW0C86d2k_lJI',
    appId: '1:243311062615:android:4b7035080336e4d2cefd12',
    messagingSenderId: '243311062615',
    projectId: 'fir-analytics-example-c69c7',
    storageBucket: 'fir-analytics-example-c69c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMSjWdH6VlKlbcqqCAcsKTyakAaXCTtXw',
    appId: '1:243311062615:ios:64d62f42c0095a6fcefd12',
    messagingSenderId: '243311062615',
    projectId: 'fir-analytics-example-c69c7',
    storageBucket: 'fir-analytics-example-c69c7.appspot.com',
    iosBundleId: 'com.example.firebaseAnalyticsExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMSjWdH6VlKlbcqqCAcsKTyakAaXCTtXw',
    appId: '1:243311062615:ios:677857ce0a3a7ef7cefd12',
    messagingSenderId: '243311062615',
    projectId: 'fir-analytics-example-c69c7',
    storageBucket: 'fir-analytics-example-c69c7.appspot.com',
    iosBundleId: 'com.example.firebaseAnalyticsExample.RunnerTests',
  );
}
